import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import AuthProvider from './context/AuthProvider';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Vision Flow Web Application</title>
        <link
          rel="icon"
          type="image/x-icon"
          href="assets/images/icon/flowicon.png"
        />
        <link rel="stylesheet" href="assets/fonts/fonts.css" />

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
          crossOrigin="anonymous"
        />

        <link rel="stylesheet" href="assets/scss/style.css" />
        <link rel="stylesheet" href="assets/scss/responsive.css"></link>
      </head>
      <body className={inter.className}>
        <Navbar />
        <AuthProvider>{children}</AuthProvider>

        {/* </SessionProviderWrapper> */}
        <Script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
          integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
          crossOrigin="anonymous"
        ></Script>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
          integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
          crossOrigin="anonymous"
        ></Script>

        <Script src="assets/js/custom.js"></Script>
      </body>
    </html>
  );
}
