name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy 
      uses: appleboy/ssh-action@master
      with:
        host: '89.117.75.222'
        username: 'root'
        port: 1024
        key: ${{ secrets.SERVER_SSH }}
        command_timeout: 200m
        script: 'cd /var/www/html/thegoldenship && ./.scripts/deploy.sh'